# Generated by Django 5.2.12 on 2026-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockproduct',
            old_name='dicount',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='stockproduct',
            name='comment',
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
    ]
