# Generated by Django 5.2.12 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_dicount_stockproduct_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='original_product_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
