# Generated by Django 6.0.3 on 2026-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockproduct_original_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='supplier',
            field=models.CharField(default='', max_length=127),
        ),
    ]
