# Generated by Django 5.2.12 on 2026-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockproduct_unit_alter_stockproduct_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='finalSellPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='sellPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
