# Generated by Django 5.2.12 on 2026-03-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stockproduct_finalsellprice_stockproduct_sellprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproduct',
            name='finalSellPrice',
        ),
        migrations.RemoveField(
            model_name='stockproduct',
            name='sellPrice',
        ),
    ]
