# Generated by Django 5.2.12 on 2026-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_mouvement', models.CharField(default='Achat', max_length=50)),
                ('quantite', models.IntegerField()),
                ('categorie', models.CharField(max_length=100)),
                ('prix_unitaire', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
