# Generated by Django 5.2.12 on 2026-03-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='prix_avant_promo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remise',
            field=models.FloatField(default=0.0),
        ),
    ]
