# Generated by Django 6.0.3 on 2026-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distant', '0002_transaction_prix_avant_promo_transaction_remise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='remise',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='prix_avant_promo',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default=0, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_product_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
