# Generated by Django 6.0.3 on 2026-03-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distant', '0003_rename_remise_transaction_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='supplier',
            field=models.CharField(default='', max_length=127),
        ),
    ]
