# Generated by Django 6.0.3 on 2026-03-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distant', '0004_alter_transaction_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_product_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
