# Generated by Django 6.0.3 on 2026-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distant', '0005_alter_transaction_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
