# Generated by Django 6.0.3 on 2026-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distant', '0006_transaction_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='original_product_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
